#!/bin/sh
### BEGIN INIT INFO
# Provides:          {{ artifactory_os_service_name }}
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       JFrog Artifactory {{ artifactory_version }} {{ artifactory_license }}
### END INIT INFO

SCRIPT="{{ artifactory_home }}/app/bin/artifactory.sh"

start() {
  {% if become_method == 'su' %}
  su -c "$SCRIPT start" {{ artifactory_os_user_name }}
  {% else %}
  sudo -u {{ artifactory_os_user_name }} $SCRIPT start
  {% endif %}

}

stop() {
  {% if become_method == 'su' %}
  su -c "$SCRIPT stop" {{ artifactory_os_user_name }}
  {% else %}
  sudo -u {{ artifactory_os_user_name }} $SCRIPT stop
  {% endif %}
}

uninstall() {
  {% if become_method == 'su' %}
  su -c "$SCRIPT uninstall" {{ artifactory_os_user_name }}
  {% else %}
  sudo -u {{ artifactory_os_user_name }} $SCRIPT uninstall
  {% endif %}
}

restart() {
  {% if become_method == 'su' %}
  su -c "$SCRIPT restart" {{ artifactory_os_user_name }}
  {% else %}
  sudo -u {{ artifactory_os_user_name }} $SCRIPT restart
  {% endif %}
}

status() {
  {% if become_method == 'su' %}
  su -c "$SCRIPT status" {{ artifactory_os_user_name }}
  {% else %}
  sudo -u {{ artifactory_os_user_name }} $SCRIPT status
  {% endif %}
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
